version: '3.8'
services:
  nginx-react:
    container_name: github_forks_view
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      NODE_ENV: production
